### ISSUE TITLE
llamaindex import issue

### ISSUE THREAD

**Issue by ghislainf** [Chainlit/literalai-typescript#66]
Hi there!
llamaindex is listed as a peer dependency but the package is currently throwing an error when llamaindex is missing.

Here's how you can see this for yourself:
- Install @literalai/client without llamaindex
- Try to load the package
- You'll see an error message saying that llamaindex is missing

A bit annoying because llamaindex has an insane number of dependencies.

Cheers! ✌🏻

**Comment by willydouhard** [comment]
Thank you for the feedback!

I opened https://github.com/Chainlit/literalai-typescript/pull/67, will test it throughout the day and will release on Monday if everything is OK.

**Comment by ghislainf** [comment]
great thanks for your reactivity!

**Comment by ghislainf** [comment]
@willydouhard I see the merge (thank you), but there's no new version available on npm. Is this normal?

**Comment by willydouhard** [comment]
Just released 0.0.517 @ghislainf, let me know if it fixes the issue on your end.

**Comment by ghislainf** [comment]
no it's not working, step to reproduce easily
```
bun add  @literalai/client
```
result 
```
bun add v1.0.3 (25e69c71)

 installed @literalai/client@0.0.517
 ```
 bun run index.ts
 ```
 import { LiteralClient } from '@literalai/client';

const client = new LiteralClient();
```
result
```
error: Cannot find package "llamaindex"
```

**Comment by willydouhard** [comment]
Nice catch, if I read this correctly it is mostly about using getters? Opened https://github.com/Chainlit/literalai-typescript/pull/69/files to address it.

**Comment by willydouhard** [comment]
Thank you for the diff! I think https://github.com/Chainlit/literalai-typescript/pull/69 covers it, WDYT?

**Comment by ghislainf** [comment]
yes it works for the import
